# Generated by Django 5.1.1 on 2024-10-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField()),
            ],
        ),
    ]
